version: '3.4'

services:
  onchainsignal:
    image: onchainsignal
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "build/src/server.js"]
