WITH VOLUME AS (
        SELECT *
        FROM
            get_volume_by_token($1, $2, $3, $4, $5)
    ), BUY_VOLUME AS (
        SELECT *
        FROM VOLUME
        WHERE
            ACTION_TYPE = 'buy'
    ),
    SELL_VOLUME AS (
        SELECT *
        FROM VOLUME
        WHERE ACTION_TYPE = 'sell'
    ),
    VOLUME_TEMPLATE AS (
		SELECT TIME_BUCKET
        FROM VOLUME
		GROUP BY TIME_BUCKET
		ORDER BY TIME_BUCKET DESC
	)
SELECT
    V.TIME_BUCKET,
    COALESCE(S.USD_VALUE, 0) AS SELL_USD_VALUE,
    COALESCE(S.COUNT, 0) AS SELL_COUNT,
    COALESCE(S.AMOUNT, 0) AS SELL_AMOUNT,
    COALESCE(B.USD_VALUE, 0) AS BUY_USD_VALUE,
    COALESCE(B.COUNT, 0) AS BUY_COUNT,
    COALESCE(B.AMOUNT, 0) AS BUY_AMOUNT,
    COALESCE(S.USD_VALUE, 0) + COALESCE(B.USD_VALUE, 0) AS TOTAL_USD_VALUE,
    COALESCE(S.COUNT, 0) + COALESCE(B.COUNT, 0) AS TOTAL_COUNT,
    COALESCE(S.AMOUNT, 0) + COALESCE(B.AMOUNT, 0) AS TOTAL_AMOUNT
FROM VOLUME_TEMPLATE V
    LEFT JOIN BUY_VOLUME B ON V.TIME_BUCKET = B.TIME_BUCKET
    LEFT JOIN SELL_VOLUME S ON V.TIME_BUCKET = S.TIME_BUCKET