WITH TOKEN_PRICE AS (
        SELECT
            TIME_BUCKET($1, TIME) AS TIME_BUCKET,
            FIRST(PRICE, TIME) AS OPEN_PRICE,
            LAST(PRICE, TIME) AS CLOSE_PRICE,
            MAX(PRICE) AS HIGH_PRICE,
            MIN(PRICE) AS LOW_PRICE
        FROM TOKEN_PRICE
				WHERE TIME >= TIMESTAMPTZ $4
				AND TIME <= TIMESTAMPTZ $5
                AND TOKEN_ID = $2
        GROUP BY TIME_BUCKET
        ORDER BY TIME_BUCKET DESC        
    ), BUY_VOLUME AS (
        SELECT *
        FROM
            get_volume_by_token($6, $2, $3, $4, $5)
        WHERE
            ACTION_TYPE = 'buy'
    ),
    SELL_VOLUME AS (
        SELECT *
        FROM
            get_volume_by_token($6, $2, $3, $4, $5)
        WHERE ACTION_TYPE = 'sell'
    )
SELECT
    P.TIME_BUCKET,
    COALESCE(S.USD_VALUE, 0) AS SELL_USD_VALUE,
    COALESCE(S.COUNT, 0) AS SELL_COUNT,
    COALESCE(S.AMOUNT, 0) AS SELL_AMOUNT,
    COALESCE(B.USD_VALUE, 0) AS BUY_USD_VALUE,
    COALESCE(B.COUNT, 0) AS BUY_COUNT,
    COALESCE(B.AMOUNT, 0) AS BUY_AMOUNT,
    COALESCE(S.USD_VALUE, 0) + COALESCE(B.USD_VALUE, 0) AS TOTAL_USD_VALUE,
    COALESCE(S.COUNT, 0) + COALESCE(B.COUNT, 0) AS TOTAL_COUNT,
    COALESCE(S.AMOUNT, 0) + COALESCE(B.AMOUNT, 0) AS TOTAL_AMOUNT,
    P.OPEN_PRICE AS OPEN_PRICE,
    P.CLOSE_PRICE as CLOSE_PRICE,
    P.HIGH_PRICE as HIGH_PRICE,
    P.LOW_PRICE AS LOW_PRICE
FROM TOKEN_PRICE P
    LEFT JOIN BUY_VOLUME B ON P.TIME_BUCKET = B.TIME_BUCKET
    LEFT JOIN SELL_VOLUME S ON P.TIME_BUCKET = S.TIME_BUCKET